vim.g.maplocalleader = " "
vim.g.vimtex_view_method = 'zathura'
vim.g.vimtex_quickfix_mode = 0


vim.cmd("nmap <localleader>ll <Plug>(vimtex-compile)")
vim.cmd("nmap <localleader>li <Plug>(vimtex-info)")
vim.cmd("nmap <localleader>lI <Plug>(vimtex-info-full)")
vim.cmd("nmap <localleader>lt <Plug>(vimtex-toc-compileopen)")
vim.cmd("nmap <localleader>lT <Plug>(vimtex-toc-toggle)")
vim.cmd("nmap <localleader>ly <Plug>(vimtex-labels-open)")
vim.cmd("nmap <localleader>lY <Plug>(vimtex-labels-toggle)")
vim.cmd("nmap <localleader>lv <Plug>(vimtex-view)")
vim.cmd("nmap <localleader>lr <Plug>(vimtex-reverse-search)")
vim.cmd("nmap <localleader>lk <Plug>(vimtex-stop)")
vim.cmd("nmap <localleader>lK <Plug>(vimtex-stop-all)")
vim.cmd("nmap <localleader>le <Plug>(vimtex-errors)")
vim.cmd("nmap <localleader>lo <Plug>(vimtex-compile-output)")
vim.cmd("nmap <localleader>lg <Plug>(vimtex-status)")
vim.cmd("nmap <localleader>lG <Plug>(vimtex-status-all)")
vim.cmd("nmap <localleader>lc <Plug>(vimtex-clean)")
vim.cmd("nmap <localleader>lC <Plug>(vimtex-clean-full)")
vim.cmd("nmap <localleader>lm <Plug>(vimtex-imaps-list)")
vim.cmd("nmap <localleader>lx <Plug>(vimtex-reload)")
vim.cmd("nmap <localleader>ls <Plug>(vimtex-toggle-main)")
vim.cmd("nmap dse   <Plug>(vimtex-env-delete)")
vim.cmd("nmap dsc   <Plug>(vimtex-cmd-delete)")
vim.cmd("nmap ds$   <Plug>(vimtex-env-delete-math)")
vim.cmd("nmap cse   <Plug>(vimtex-env-change)")
vim.cmd("nmap csc   <Plug>(vimtex-cmd-change)")
vim.cmd("nmap cs$   <Plug>(vimtex-cmd-change-math)")
vim.cmd("nmap tse   <Plug>(vimtex-env-toggle-star)")
vim.cmd("map tsd   <Plug>(vimtex-delim-toggle-modifier)")
vim.cmd("map<F7>   <Plug>(vimtex-cmd-create)")
vim.cmd("map]]   <Plug>(vimtex-delim-close)")
vim.cmd("map ac   <Plug>(vimtex-ac)")
vim.cmd("map ic   <Plug>(vimtex-ic)")
vim.cmd("map ad   <Plug>(vimtex-ad)")
vim.cmd("map id   <Plug>(vimtex-id)")
vim.cmd("map ae   <Plug>(vimtex-ae)")
vim.cmd("map ie   <Plug>(vimtex-ie)")
vim.cmd("map a$   <Plug>(vimtex-a$)")
vim.cmd("map i$   <Plug>(vimtex-i$)")
vim.cmd("map %   <Plug>(vimtex-%)")
vim.cmd("map ]]   <Plug>(vimtex-]])")
vim.cmd("map ][   <Plug>(vimtex-][)")
vim.cmd("map []   <Plug>(vimtex-[])")
